
const bcrypt = require('bcrypt-nodejs');


exports.seed = function(knex) {
  const obterHash = (password, callback) => {
    bcrypt.genSalt(10, (err, salt) => {
        bcrypt.hash(password, salt, null, (err, hash) => callback(hash))
    })
  }
  return knex('users').del()
    .then(function () {
      return knex('users').insert([
        {
          id: 1,
          login: 'admin',
          password: '$2a$10$1UWEIjDoSpXbn0EqFB5tKewKvQ32D/zeYoNYP6M1oJNaVhrqR/VjG',
          type_user: 'administrator',
          birth: null,
          username: 'Severino',
          cpf_cnpj: '12234389887',
          rg: '459227142',
          street: 'Rua São Sebastião',
          n_house: '549',
          neighborhood: 'Vila Nossa Senhora de Fátima',
          zip_code: '14405359',
          city: 'Franca',
          uf: 'SP',
          complement: '',
          picture: '',
          company: true,
          status_login: false,
          status_active: 'active',
          checked: false,
          sex: null,
          marital_status: null,
          create_at: new Date()
        },
        {
          id: 2,
          login: 'edu789henrique@gmail.com',
          password: '$2a$10$1UWEIjDoSpXbn0EqFB5tKewKvQ32D/zeYoNYP6M1oJNaVhrqR/VjG',
          type_user: 'client',
          birth: '2000-07-25',
          username: 'Eduardo Henrique',
          cpf_cnpj: '44647862860',
          rg: '344874692',
          street: 'Rua Paulo Fernandez de Carvalho',
          n_house: '960',
          neighborhood: 'Chacaras São Paulo',
          zip_code: '14406608',
          city: 'Franca',
          uf: 'SP',
          complement: '',
          picture: '/uploads/profile_photos/1.jpeg',
          company: false,
          status_login: true,
          status_active: 'active',
          checked: false,
          sex: 'M',
          marital_status: 'single',
          create_at: new Date()
        },
        {
          id: 3,
          login: 'carlosalexandremartins..carlosalexandremartins@bzness.com.br',
          password: '$2a$10$1UWEIjDoSpXbn0EqFB5tKewKvQ32D/zeYoNYP6M1oJNaVhrqR/VjG',
          type_user: 'client',
          birth: '1967-04-09',
          username: 'Carla Martins',
          cpf_cnpj: '73079819802',
          rg: '344874692',
          street: 'Praça Gleuce Finatti',
          n_house: '738',
          neighborhood: 'Vila Rezende',
          zip_code: '14406529',
          city: 'Franca',
          uf: 'SP',
          complement: '',
          picture: '/uploads/profile_photos/3.png',
          company: false,
          status_login: true,
          status_active: 'active',
          checked: false,
          sex: 'M',
          marital_status: 'single',
          create_at: new Date()
        },
        {
          id: 4,
          login: 'raimundomartinisaacmoraes__raimundomartinisaacmoraes@lumavale.com.br',
          password: '$2a$10$1UWEIjDoSpXbn0EqFB5tKewKvQ32D/zeYoNYP6M1oJNaVhrqR/VjG',
          type_user: 'service provider',
          birth: '1949-08-26',
          username: 'Raimundo Martin Isaac Moraes',
          cpf_cnpj: '20137658869',
          rg: '387533266',
          street: 'Vila Almir',
          n_house: '990',
          neighborhood: 'Centro',
          zip_code: '14400589',
          city: 'Franca',
          uf: 'SP',
          complement: '',
          picture: '/uploads/profile_photos/4.jpg',
          company: false,
          status_login: true,
          status_active: 'active',
          checked: false,
          sex: 'M',
          marital_status: 'single',
          create_at: new Date()
        },
        {
          id: 5,
          login: 'emanuellysophiadacruz..emanuellysophiadacruz@pibnet.com.br',
          password: '$2a$10$1UWEIjDoSpXbn0EqFB5tKewKvQ32D/zeYoNYP6M1oJNaVhrqR/VjG',
          type_user: 'service provider',
          birth: '1949-08-26',
          username: 'Emanuelly Sophia da Cruz',
          cpf_cnpj: '16162135829',
          rg: '491636672',
          street: 'Praça Alberto de Paula',
          n_house: '391',
          neighborhood: 'São Joaquim',
          zip_code: '14406369',
          city: 'Franca',
          uf: 'SP',
          complement: '',
          picture: '/uploads/profile_photos/5.jpg',
          company: false,
          status_login: true,
          status_active: 'active',
          checked: false,
          sex: 'F',
          marital_status: 'single',
          create_at: new Date()
        },
        {
          id: 6,
          login: 'danilojoaquimcaiomoraes..danilojoaquimcaiomoraes@negleribeiro.com',
          password: '$2a$10$1UWEIjDoSpXbn0EqFB5tKewKvQ32D/zeYoNYP6M1oJNaVhrqR/VjG',
          type_user: 'service provider',
          birth: '1976-03-15',
          username: 'Danilo Joaquim Caio Moraes',
          cpf_cnpj: '78179724867',
          rg: '235875351',
          street: 'Praça Doutor Dácio Alves Ferreira',
          n_house: '795',
          neighborhood: 'Residencial Meireles',
          zip_code: '14407250',
          city: 'Franca',
          uf: 'SP',
          complement: '',
          picture: '/uploads/profile_photos/2.png',
          company: false,
          status_login: true,
          status_active: 'active',
          checked: false,
          sex: 'M',
          marital_status: 'married',
          create_at: new Date()
        },
        {
          id: 7,
          login: 'bryanhugocastro__bryanhugocastro@badauy.com',
          password: '$2a$10$1UWEIjDoSpXbn0EqFB5tKewKvQ32D/zeYoNYP6M1oJNaVhrqR/VjG',
          type_user: 'service provider',
          birth: '1976-03-15',
          username: 'Bryan Hugo Castro',
          cpf_cnpj: '70235169803',
          rg: '408975933',
          street: 'Rua José Osmar Leite',
          n_house: '441',
          neighborhood: 'Residencial Itapuã',
          zip_code: '14406295',
          city: 'Franca',
          uf: 'SP',
          complement: '',
          picture: '/uploads/profile_photos/7.jpg',
          company: false,
          status_login: true,
          status_active: 'active',
          checked: false,
          sex: 'M',
          marital_status: 'married',
          create_at: new Date()
        },
      ]);
    });
};
